<div class="content-holder">
    <div class="content-header">
        <div class="container-fluid text-capitalize">
            <div class="pull-left">
                manage products
            </div>
            <div class="pull-right">
                <a href="<?=$this->url('catalog/product/create')?>" 
                   role="button" 
                   class="btn btn-danger btn-xs">
                    <i class="fa fa-plus"></i>
                </a>
            </div>
        </div>
        
    </div>
    <div class="content-body">
        <div class="container-fluid">
            This is my contents
        </div>
    </div>
</div>